from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, ConfigDict  # <--- Note: ConfigDict is imported here
from typing import Optional, List, Any

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class BaseRequest(BaseModel):
    # ▼▼▼ THIS IS THE MISSING PART THAT FIXES THE STUCK BUTTON ▼▼▼
    model_config = ConfigDict(extra='allow') 
    # ▲▲▲ This tells the server to accept ANY extra fields (like content_type)
    
    language: Optional[str] = "en"
    username: Optional[str] = None
    topic: Optional[str] = None
    repository: Optional[str] = None

@app.get("/api/v1/status")
async def status():
    return {"status": "operational"}

@app.post("/api/v1/github/analyze")
async def analyze(req: BaseRequest):
    return {
        "insights": {
            "analysis_results": ["User is active", "Python expert"], 
            "total_users": 1, 
            "language": req.language
        },
        "status": "completed"
    }

@app.post("/api/v1/content/generate")
async def generate(req: BaseRequest):
    # Now this will work because 'req' accepts the extra data silently!
    return {
        "content": f"AI Generated Content for: {req.topic or 'your topic'}\n\n(Generated by Dingo Marketing)", 
        "status": "completed"
    }

@app.post("/api/v1/community/engage")
async def engage(req: BaseRequest):
    return {
        "engagement_result": {"raw": "Community engagement successful"}, 
        "status": "completed"
    }